### ISSUE TITLE
it isn't the exact same order ;)

### ISSUE THREAD

**Issue by kkoo95** [paleite/stylelint-config-chrome-devtools-order#1]
Devtools does an additional alphabetical sort in each category. So something like `properties: properties.sort()` in config-creator should do it.
Also, based on [stylelint-order docs](https://github.com/hudochenkov/stylelint-order/tree/master/rules/properties-order#options), it's not `categoryName` but `groupName`

Thank you for this plugin

**Comment by paleite** [comment]
Awesome feedback! Will be looking into this 🙂  Thanks for the hints, also

**Comment by paleite** [comment]
Hi again!
I've pushed a new (canary) version which addresses all of the above: https://www.npmjs.com/package/stylelint-config-chrome-devtools-order/v/0.0.3-0

Thanks again for letting me know, and please let me know if any other issue arises. 🙂
